Models/ScoreSheet.cs
using System;
using System.Collections.Generic;

namespace OBGpgm.Models
{
    public partial class ScoreSheet
    {
        public int SsSessionId { get; set; }
        public int SsDivision { get; set; }
        /// <summary>
        /// Week Number
        /// </summary>
        public int SsWeek { get; set; }
        /// <summary>
        /// Team Number
        /// </summary>
        public int SsHteam { get; set; }
        /// <summary>
        /// Team Number
        /// </summary>
        public int SsVteam { get; set; }
        public int SsHpoints { get; set; }
        public int SsVpoints { get; set; }
        /// <summary>
        /// Date of match
        /// </summary>
        public DateTime? SsDate { get; set; }

        public virtual Session SsSession { get; set; } = null!;
    }
}

Controllers/ScoreSheetsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using OBGpgm.Data;
using OBGpgm.Models;
using OBGpgm.Interfaces;
using OBGpgm.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Hosting;
using Microsoft.Office.Interop.Excel;
using Excel = Microsoft.Office.Interop.Excel;
using System;
using static System.Net.Mime.MediaTypeNames;
using Microsoft.AspNetCore.Http;

namespace OBGpgm.Controllers
{
    public class ScoreSheetsController : Controller
    {
        private readonly ObgDbContext _context;
        private readonly HttpClient client = null;
        private readonly IMemberRepository memberRepository;
        private readonly IPlayerRepository playerRepository;
        private readonly IScheduleRepository scheduleRepository;
        private readonly ISessionRepository sessionRepository;
        private readonly IScoreSheetRepository scoreSheetRepository;
        private readonly ISharkRepository sharkRepository;
        private readonly ITeamRepository teamRepository;
        private readonly IWebHostEnvironment hostEnvironment;
        public ScoreSheetsController(ObgDbContext context,
                                HttpClient client,
                                ISharkRepository sharkRepository,
                                IMemberRepository memberRepository,
                                IPlayerRepository playerRepository,
                                IScheduleRepository scheduleRepository,
                                IScoreSheetRepository scoreSheetRepository,
                                ISessionRepository sessionRepository,
                                ITeamRepository teamRepository,
                                IWebHostEnvironment hostEnvironment,
                                IConfiguration config)
        {
            _context = context;
            this.client = client;
            this.sharkRepository = sharkRepository;
            this.memberRepository = memberRepository;
            this.playerRepository = playerRepository;
            this.scoreSheetRepository = scoreSheetRepository;
            this.scheduleRepository = scheduleRepository;
            this.sessionRepository = sessionRepository;
            this.teamRepository = teamRepository;
            this.hostEnvironment = hostEnvironment;
        }


        // Constant arrays used for table assignment
        private readonly string[] pairsPerSession = { "", "", "", "", "", "", "", "",
                                            "4", "4", "3 2", "3 2", "3 3", "3 3", "4 3", "4 3", "4 4",
                                            "", "3 3 3", "", "4 3 3", "", "4 4 3", "", "4 4 4"};

        private readonly string[] tablesToAssign = { "", "", "1&2 5&6", "1&2 5&6 7&8", "1&2 3&4 5&6 7&8" }
        ;
        private readonly string[] timeSlots = { "", "11:00", "12:45", "2:30" };

        public async Task<IActionResult> ListAsync(string session, string week)
        {
            await FillSessionsAsync();

            // Get the current session
            Session csession = sessionRepository.SelectByCurrent();

            if (String.IsNullOrEmpty(session))
            {
                if (HttpContext.Session.GetString("Year") == null)
                {
                    session = csession.SessionId.ToString();
                    week = csession.CurrentWeek;
                }
                else
                {
                    session = HttpContext.Session.GetString("Session");
                    week = HttpContext.Session.GetString("Week");
                }
            }
            
            ViewData["Week"] = week;
            ViewData["Session"] = session;
            HttpContext.Session.SetString("Session", session);
            HttpContext.Session.SetString("Week", week);
            int sid = Convert.ToInt32(session);
            await FillWeeksAsync(sid);
            bool found = false;
            foreach (SelectListItem item in ViewBag.Weeks)
            {
                if(item.Text == week)
                {
                    found = true;
                    break;
                }
            }
            if(!found)
            {
                week = ViewBag.Week;
            }
            List<ScoreSheet> data = scoreSheetRepository.SelectAllByWeek(sid, Convert.ToInt32(week));

            return View(data);
        }
        public IActionResult Get(int id, int week, int hteam)
        {
            ScoreSheet model = scoreSheetRepository.SelectByID(id, week, hteam);
            return View(model);
        }
        // DETAILS: ScoreSheets/Details
        public IActionResult Details(int id, int week, int hteam, int pg = 1)
        {     
            ScoreSheet scoresheet = scoreSheetRepository.SelectByID(id, week, hteam);
                
            if (scoresheet == null)
            {
                return NotFound();
            }

            ViewBag.returnPage = pg;
            return View(scoresheet);
        }

        // GET: ScoreSheets/Edit/5
        public IActionResult Edit(int id, int week, int hTeam, int pg = 1)
        {
            if (id == null || _context.ScoreSheets == null)
            {
                return NotFound();
            }

            var scoresheet = scoreSheetRepository.SelectByID(id, week, hTeam);
            if (scoresheet == null)
            {
                return NotFound();
            }
            ViewBag.returnPage = pg;
            return View(scoresheet);
        }


        public IActionResult Insert(int pg=1)
        {
            ViewBag.returnPage = pg;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Insert(ScoreSheet model)
        {
            if (ModelState.IsValid)
            {
                scoreSheetRepository.Insert(model);
                ViewBag.Message = "ScoreSheet inserted successfully!";
            }
            return View(model);
        }
        public IActionResult Update(int id, int week, int hteam)
        {
            ScoreSheet model = scoreSheetRepository.SelectByID(id, week, hteam);
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(ScoreSheet model)
        {
            if (ModelState.IsValid)
            {
                scoreSheetRepository.Update(model);
                ViewBag.Message = "ScoreSheet updated successfully!";
            }
            return View(model);
        }

        [ActionName("Delete")]
        public IActionResult ConfirmDelete(int id, int week, int hteam)
        {
            ScoreSheet model = scoreSheetRepository.SelectByID(id, week, hteam);
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int id, int week, int hteam)
        {
            {
                scoreSheetRepository.Delete(id, week, hteam);
                TempData["Message"] = "ScoreSheet deleted successfully!";
            }
            return RedirectToAction("List");
        }


        public async Task<IActionResult> EnterAsync()
        {
            await FillPointsAsync();
            await FillSessionsAsync();
            // Get the current session
            Session csession = sessionRepository.SelectByCurrent();

            string thisSession = "";
            string curWeek = "1";

            if (String.IsNullOrEmpty(thisSession))
            {
                if (HttpContext.Session.GetString("thisSession") == null)
                {
                    thisSession = csession.SessionId.ToString();
                    curWeek = "1";
                }
                else
                {
                    thisSession = HttpContext.Session.GetString("thisSession");
                    curWeek = HttpContext.Session.GetString("curWeek");
                }
            }

            ViewBag.vPointsEnabled = false;

            ViewData["thisSession"] = thisSession;
            HttpContext.Session.SetString("thisSession", thisSession);
            ViewData["curWeek"] = curWeek;
            HttpContext.Session.SetString("curWeek", curWeek);

            int id = Convert.ToInt32(thisSession);
            Session tSess = sessionRepository.SelectById(id);
            int sid = tSess.SessionId;
            int wid = Convert.ToInt32(tSess.CurrentWeek);

            ViewBag.Captains = playerRepository.SelectAllByCaptain(sid);

            List<ScoreSheet> data = scoreSheetRepository.SelectAllByWeek(sid, wid);
            return View(data);
        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EnterAsync(List<ScoreSheet> model)
        {
            if (!ModelState.IsValid)
            {

            }

            // Get the current session
            Session csession = sessionRepository.SelectByCurrent();

            foreach (ScoreSheet ss in model)
            {
                // Get the high score by a team this session
                int highScore = sharkRepository.SelectHighBySession(ss.SsSessionId);

                scoreSheetRepository.Update(ss);
                TempData["Message"] = "ScoreSheet updated successfully!";
                // Did this home team make a high score for session?
                if (ss.SsHpoints >= highScore)
                {
                    //int points = ss.SsHpoints ?? default(int);
                    int points = ss.SsHpoints;
                    await UpdateSharks(ss, ss.SsHteam, points);
                }

                highScore = sharkRepository.SelectHighBySession(ss.SsSessionId);

                // Did this viitor make a high score for session?
                if (ss.SsVpoints >= highScore)
                {
                    //int points = ss.SsVpoints ?? default(int);
                    //int Vteam = ss.SsVteam ?? default(int);
                    int points = ss.SsVpoints;

Views/ScoreSheets/Create.cshtml
@model OBGpgm.Models.ScoreSheet
@{
    @* ViewData["Title"] = "Create Score Sheets"; *@
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section Scripts{
    <script>
        /* this script sets the two dropdowns for year and season */
        $(function () {
            $("span.id_100 select").val("@ViewData["session"]");
            $("span.id_200 select").val("@ViewData["numWeeks"]");
            $("input#startDate").val("@ViewData["startDate"]");
            $("input#skipDate").val("@ViewData["skipDate"]");
            $("input#skipList").val("@ViewBag.skipList");
        })


    </script>
}
<div class="container">
    <h1>Create Score Sheets</h1>    `

    <h3 class="message text-success">@TempData["Message"]</h3>

    <form asp-controller="ScoreSheets" asp-action="Create" method="post">
        <div class="form-actions no-color">
            <div class="form-row mb-5">
                <div class="form-group col-sm-4">
                    <label class="col-form-label" style="text-align: right">Session</label>
                    <span class="id_100">
                        <select asp-items="@ViewBag.SessionId" id="session" name="session" class="col-sm-4">
                            <option value="">Please select</option>
                        </select>
                    </span>
                </div>
            </div>

            <div class="form-row">
                    <input type="submit" name="submit" value="Create" class="btn btn-primary" /> |
                    <input type="submit" name="submit" value="Make Printable" class="btn btn-secondary" />
            </div>
        </div>
    </form>
</div>

Views/ScoreSheets/CreateOld.cshtml
@model OBGpgm.Models.ScoreSheet
@{
    @* ViewData["Title"] = "Create Score Sheets"; *@
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section Scripts{
    <script>
        /* this script sets the two dropdowns for year and season */
        $(function () {
            $("span.id_100 select").val("@ViewData["session"]");
            $("span.id_200 select").val("@ViewData["numWeeks"]");
            $("input#startDate").val("@ViewData["startDate"]");
            $("input#skipDate").val("@ViewData["skipDate"]");
            $("input#skipList").val("@ViewBag.skipList");
        })


    </script>
}
<div class="container">
    <h1>Create Score Sheets</h1>    `

    <h3 class="message text-success">@TempData["Message"]</h3>

    <form asp-controller="ScoreSheets" asp-action="Create" method="post">
        <div class="form-actions no-color">
            <div class="form-row">
                <div class="form-group col-sm-4">
                    <label class="col-form-label" style="text-align: right">Session</label>
                    <span class="id_100">
                        <select asp-items="@ViewBag.SessionId" id="session" name="session" class="col-sm-4">
                            <option value="">Please select</option>
                        </select>
                    </span>
                </div>



                <div class="form-group col-sm-4">
                    <label class="col-sm-5 col-form-label"
                           style="text-align:right">Weeks to play</label>
                    <span class="id_200">
                        <select id="numWeeks" name="numWeeks" class="col-sm-5">
                            <option value="">Select weeks</option>
                            <option value="1">1</option>
                            <option value="2">2</option>
                            <option value="3">3</option>
                            <option value="4">4</option>
                            <option value="5">5</option>
                            <option value="6">6</option>
                            <option value="7">7</option>
                            <option value="8">8</option>
                            <option value="9">9</option>
                            <option value="10">10</option>
                            <option value="11">11</option>
                            <option value="12">12</option>
                        </select>
                    </span>
                </div>


                <div class="form-group col-sm-4">
                    <span class="id_300">
                        <label class="col-form-label">Start Date</label>
                        <input id="startDate" name="startDate" type="date" class="col-sm-6" />
                    </span>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-sm-4">
                    <span class="id_400">
                        <label class="col-form-label">Skip Date</label>
                        <input id="skipDate" name="skipDate" type="date" class="col-sm-6" />
                    </span>
                </div>
                <div class="form-group col-sm-2">
                    <div class="form-row">
                        <input type="submit" name="submit" value="Add" class="btn btn-primary" />
                    </div>
                </div>
                <div class="form-group col-sm-4">
                    <input hidden="hidden" id="skipList" name="skipList" />
                    <label class="col-form-label">Skip List</label>
                    @if (ViewBag.skipList != null)
                    {
                        List<string> slist = (@ViewBag.skipList);
                        @foreach (string item in slist)
                        {
                            <div>@item</div>
                        }
                    }
                </div>
            </div>
            <div class="form-row">
                <input type="submit" name="submit" value="Create" class="btn btn-primary" /> |
                <a asp-action="Create">Session Archives</a>
            </div>
        </div>
    </form>
</div>

Views/ScoreSheets/Delete.cshtml
@model OBGpgm.Models.ScoreSheet

@{
    ViewData["Title"] = "Delete Score Sheet";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <h1>Delete Score Sheet</h1>

    <h3>Are you sure you want to delete this?</h3>
    <h4>ScoreSheet</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SsDivision)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SsDivision)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SsVteam)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SsVteam)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SsHpoints)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SsHpoints)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SsVpoints)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SsVpoints)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SsDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SsDate)
        </dd>

    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="SsSessionId" />
        <input type="hidden" asp-for="SsWeek" />
        <input type="hidden" asp-for="SsHteam" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/ScoreSheets/Details.cshtml
@model OBGpgm.Models.ScoreSheet

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var returnPage = Convert.ToInt32(ViewBag.returnPage);
}

<h1>Details</h1>

<div>
    <h4>ScoreSheet</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.SsDivision)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.SsDivision)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.SsVteam)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.SsVteam)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.SsHpoints)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.SsHpoints)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.SsVpoints)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.SsVpoints)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.SsDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.SsDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.SsSession)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.SsSessionId)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Index" asp-route-pg="@returnPage">Back to List</a>
</div>

Views/ScoreSheets/Edit.cshtml
@model OBGpgm.Models.ScoreSheet

@{
    ViewData["Title"] = "Update ScoreSheet";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var returnPage = Convert.ToInt32(ViewBag.returnPage);
}

<div class="container">
    <h1>Edit</h1>

    <h4>Update ScoreSheet</h4>
    <hr />
    <div class="row">
        <div class="col-md-8">
            <form asp-action="Update">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-row">
                    <div class="form-group col-md-4">
                        <label asp-for="SsSessionId" class="control-label"></label>
                        <input asp-for="SsSessionId" class="form-control" disabled="disabled" />
                        <span asp-validation-for="SsSessionId" class="text-danger"></span>
                    </div>
                    <div class="form-group col-md-4">
                        <label asp-for="SsDivision" class="control-label"></label>
                        <input asp-for="SsDivision" class="form-control" disabled="disabled" />
                        <span asp-validation-for="SsDivision" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-4">
                        <label asp-for="SsWeek" class="control-label"></label>
                        <input asp-for="SsWeek" class="form-control" disabled="disabled" />
                        <span asp-validation-for="SsWeek" class="text-danger"></span>
                    </div>
                    <div class="form-group col-md-4">
                        <label asp-for="SsDate" class="control-label"></label>
                        <input asp-for="SsDate" class="form-control" disabled="disabled" />
                        <span asp-validation-for="SsDate" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-4">
                        <label asp-for="SsHteam" class="control-label"></label>
                        <input asp-for="SsHteam" class="form-control" disabled="disabled" />
                        <span asp-validation-for="SsHteam" class="text-danger"></span>
                    </div>
                    <div class="form-group col-md-4">
                        <label asp-for="SsHpoints" class="control-label"></label>
                        <input asp-for="SsHpoints" class="form-control" />
                        <span asp-validation-for="SsHpoints" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-4">
                        <label asp-for="SsVteam" class="control-label"></label>
                        <input asp-for="SsVteam" class="form-control" disabled="disabled" />
                        <span asp-validation-for="SsVteam" class="text-danger"></span>
                    </div>
                    <div class="form-group col-md-4">
                        <label asp-for="SsVpoints" class="control-label"></label>
                        <input asp-for="SsVpoints" class="form-control" />
                        <span asp-validation-for="SsVpoints" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group">
                        <input type="submit" value="Save" class="btn btn-primary" />
                    </div>
                </div>
            </form>
        </div>
    </div>

    <div>
        <a asp-action="Index" asp-route-pg="@returnPage">Back to List</a>
    </div>

    @section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }
</div>

Views/ScoreSheets/Enter.cshtml
@model List<ScoreSheet>

@{
    ViewData["Title"] = "Enter Scores";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section Scripts{
    <script>
        /* this script sets the two dropdowns for year and season */
        $(function () {
            $("select#thisSession").val("@ViewData["thisSession"]");
            $("select#curWeek").val("@ViewData["curWeek"]");
            //debugger;

        });

        function DoUpdate(hp) {
            // hp is node of <select> for home team
            // parent is node of <div> for home select
            var parent = hp.parentNode;

            // grandDad is node of <div> for group
            var grandDad = parent.parentNode;

            // mod is node of <div> for row
            var mod = grandDad.parentNode;

            // all is node of <div> for container
            var all = mod.parentNode;

            // vp is node of <select> for visitor
            var vp = grandDad.querySelector('select.visitor');
            var option = hp.options[hp.selectedIndex];
            if (option.value != "Enter score") {
                $(vp).find('option:not(:first)')
                    .remove();
                vp.classList.add('done');
                var vCount = 17 - option.value;
                for (var i = 0; i < vCount; i++) {
                    var opt = document.createElement('option');
                    opt.value = i.toString();
                    opt.text = i.toString();
                    if (i == (vCount - 1)) {
                        opt.selected = true;
                    }
                    vp.add(opt, null);
                }
                vp.disabled = null;
            }
            //debugger;
            // enable enter button when all scores entered
            var visitors = all.querySelectorAll('select.visitor');
            var done = all.querySelectorAll('select.done');
            if (done.length == visitors.length) {
                var enter = document.getElementById("submit");
                enter.disabled = null;
            }
        }

    </script>
}
<div class="container">
    <h1>Enter Scores</h1>
    <h3 class="message text-success">@TempData["Message"]</h3>
    <form name="form2" asp-controller="ScoreSheets" asp-action="Enter" method="post">
        <table class="table">
            <thead>
                <tr>
                    <th scope="col"><h5 class="control-label">Session</h5></th>
                    <th scope="col"><h5 class="control-label">Date</h5></th>
                    <th scope="col"><h5 class="control-label">Home Team</h5></th>
                    <th scope="col"><h5 class="control-label">Captain</h5></th>
                    <th scope="col"><h5 class="control-label">Score</h5></th>
                        <th scope="col"><h5 class="control-label">Visitor</h5></th>
                        <th scope="col"><h5 class="control-label">Captain</h5></th>
                    <th scope="col"><h5 class="control-label">Score</h5></th>
                </tr>
            </thead>
            <tbody>
                @for (int i = 0; i < Model.Count; i++)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(m => m[i].SsSessionId)
                            <input type="hidden" asp-for="@Model[i].SsSessionId" />
                        </td>
                        <td>
                            @Convert.ToDateTime(Model[i].SsDate).ToString("MM/dd/yyyy")
                            <input type="hidden" asp-for="@Model[i].SsDate" />
                        </td>
                        <td>
                            @Html.DisplayFor(m => m[i].SsHteam)
                            <input type="hidden" asp-for="@Model[i].SsHteam" />
                        </td>
                        <td>
                            @{
                                foreach (Player c in ViewBag.Captains){
                                    if (Model[i].SsHteam == c.Team.TeamNumber){
                                        string capt = c.Member.LastName;
                                        @(capt)
                                        break;
                                    }
                                }
                            } 
                        </td>
                        <td>
                            <select name="@Html.NameFor(m => m[i].SsHpoints)"
                                class="home"
                                onchange="DoUpdate(this)"
                                asp-for="@Model[i].SsHpoints">
                                <option value="0">Enter score</option>
                                <option value="0">0</option>
                                <option value="1">1</option>
                                <option value="2">2</option>
                                <option value="3">3</option>
                                <option value="4">4</option>
                                <option value="5">5</option>
                                <option value="6">6</option>
                                <option value="7">7</option>
                                <option value="8">8</option>
                                <option value="9">9</option>
                                <option value="10">10</option>
                                <option value="11">11</option>
                                <option value="12">12</option>
                                <option value="13">13</option>
                                <option value="14">14</option>
                                <option value="15">15</option>
                                <option value="16">16</option>
                            </select>
                        </td>
                        <td>
                            @Html.DisplayFor(m => m[i].SsVteam)
                            <input type="hidden" asp-for="@Model[i].SsVteam" />
                        </td>
                        <td>
                            @{
                                foreach (Player c in ViewBag.Captains)
                                {
                                    if (Model[i].SsVteam == c.Team.TeamNumber)
                                    {
                                        string capt = c.Member.LastName;
                                        @(capt)
                                        break;
                                    }
                                }
                            }
                        </td>
                        <td>
                            <select name="@Html.NameFor(m => m[i].SsVpoints)"
                                class="visitor"
                                disabled="disabled"
                                asp-for="@Model[i].SsVpoints">
                                <option value="">Enter score</option>
                            </select>
                            <input type="hidden" asp-for="@Model[i].SsDivision" />
                            <input type="hidden" asp-for="@Model[i].SsWeek" />
                        </td>
                    </tr>                    
                }                     
            </tbody>
        </table>
        
        <div class="form-row row">
            <div class="col-2">
                <input type="submit" id="submit" name="submit"
                        disabled="disabled" method="post"
                        value="Enter" class="btn btn-primary" />
            </div>
        </div>
    </form>
</div>